<?php
// =============================================================================
// 공통 유틸 — 이스케이프, URL 안전화, 날짜, i18n
// =============================================================================
declare(strict_types=1);

/** HTML 이스케이프. 화면에 값을 찍을 때는 예외 없이 이걸 통과시킵니다. */
function e(?string $s): string
{
    return htmlspecialchars((string)$s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

/**
 * href 에 넣어도 되는 URL 인지 검사합니다.
 * 관리자가 입력한 값이 그대로 링크가 되므로, javascript: 같은 스킴이 저장되어도
 * 실행되지 않도록 http/https 만 통과시킵니다.
 */
function safe_url(?string $url): ?string
{
    $url = trim((string)$url);
    if ($url === '') {
        return null;
    }
    $scheme = strtolower((string)parse_url($url, PHP_URL_SCHEME));
    return in_array($scheme, ['http', 'https'], true) ? $url : null;
}

function obs_url(string $key): string
{
    return rtrim(OBS_BASE_URL, '/') . '/' . ltrim($key, '/');
}

function human_size(int $bytes): string
{
    $units = ['B', 'KB', 'MB', 'GB'];
    $i = 0;
    $n = (float)$bytes;
    while ($n >= 1024 && $i < count($units) - 1) {
        $n /= 1024;
        $i++;
    }
    return ($i === 0 ? (string)(int)$n : number_format($n, 1)) . ' ' . $units[$i];
}

/** OBS 의 UTC 타임스탬프를 표시용 현지 시각으로 바꿉니다. */
function fmt_date(?string $iso, string $format = 'Y-m-d'): string
{
    if (!$iso) {
        return '';
    }
    try {
        return (new DateTimeImmutable($iso))
            ->setTimezone(new DateTimeZone(DISPLAY_TZ))
            ->format($format);
    } catch (Exception $ex) {
        return '';
    }
}

// -----------------------------------------------------------------------------
// i18n — 헤더와 UI 문구만 번역합니다. 도구명·OS·제품명 같은 데이터 값은
// 어차피 영문 식별자라 번역 대상이 아닙니다.
// -----------------------------------------------------------------------------

const I18N = [
    'en' => [
        'login_title'    => 'Administrator sign-in',
        'login_sub'      => 'Sign in to edit the table.',
        'login_btn'      => 'Sign in',
        'login_back'     => '← View the table without signing in',
        'login_hint'     => 'Temporary sign-in used until SSO is wired up. The account lives in lib/config.php.',
        'login_failed'   => 'Wrong ID or password.',
        'logout'         => 'Sign out',
        'signin'         => 'Admin sign-in',
        'inventory'      => 'Inventory List (Total %d)',
        'search_ph'      => 'Search tools...',
        'lang_btn'       => '한글로 변경',
        'theme_light'    => 'Light',
        'theme_dark'     => 'Dark',
        'edit'           => 'Edit',
        'delete'         => 'Delete',
        'add_tool'       => 'Add Tool',
        'save'           => 'Save',
        'cancel'         => 'Cancel',
        'add_row'        => '+ Add',
        'latest'         => 'LATEST',
        'older'          => 'Older versions (%d)',
        'view_all'       => 'View all (%d) →',
        'no_artifact'    => 'no artifact in OBS',
        'no_match'       => 'No tools match your search.',
        'no_tools'       => 'No tools registered yet.',
        'cache_ok'       => 'OBS cache updated: %s',
        'cache_none'     => 'OBS cache unavailable',
        'auth_off'       => 'SSO is <b>disabled</b>. Turn AUTH_MODE to <code>sso</code> in lib/config.php to switch over.',
        'not_found_msg'  => 'If you cannot find the tool you are looking for, please visit the link below.',
        'footer'         => 'Corporate Infra Development Team / Unauthorized access is strictly prohibited.',
        'generated'      => 'Generated: %s',
        'confirm_del'    => 'Delete "%s"? This cannot be undone from the page.',
        'saved'          => 'Saved.',
        'deleted'        => 'Deleted.',
        'conflict'       => 'Someone else changed the table while you were editing. Reload and try again.',
        'f_tool'         => 'Tool name',
        'f_prefix'       => 'OBS prefix',
        'f_os'           => 'OS / ARCH supported',
        'f_product'      => 'Product supported',
        'f_manual'       => 'Manual links',
        'f_rm_text'      => 'Remarks — note',
        'f_rm_links'     => 'Remarks — links',
        'f_locked'       => 'From OBS — not editable',
        'f_locked_desc'  => 'Tool link · Older versions · Verification report are generated by matching obs_prefix.',
        'ph_label'       => 'Label',
        'ph_url'         => 'https://...',
        'ph_multi'       => 'One per line',
        'ph_note'        => 'e.g. Emergency Fix',
        'modal_edit'     => 'Edit tool — %s',
        'modal_add'      => 'Add tool',
        'headers'        => ['Tool', 'OS / ARCH Supported', 'Product Supported',
                             'Tool link', 'Verification Report', 'Manual', 'Remarks'],
    ],
    'ko' => [
        'login_title'    => '관리자 로그인',
        'login_sub'      => '표를 수정하려면 로그인이 필요합니다.',
        'login_btn'      => '로그인',
        'login_back'     => '← 로그인 없이 표만 보기',
        'login_hint'     => 'SSO 전환 전까지 쓰는 임시 로그인입니다. 계정은 lib/config.php 에 있습니다.',
        'login_failed'   => 'ID 또는 비밀번호가 올바르지 않습니다.',
        'logout'         => '로그아웃',
        'signin'         => '관리자 로그인',
        'inventory'      => '도구 인벤토리 리스트 (총 %d개)',
        'search_ph'      => '도구 검색...',
        'lang_btn'       => 'English',
        'theme_light'    => '라이트',
        'theme_dark'     => '다크',
        'edit'           => '수정',
        'delete'         => '삭제',
        'add_tool'       => '도구 추가',
        'save'           => '저장',
        'cancel'         => '취소',
        'add_row'        => '+ 추가',
        'latest'         => '최신',
        'older'          => '이전 버전 (%d)',
        'view_all'       => '전체 보기 (%d) →',
        'no_artifact'    => 'OBS에 산출물 없음',
        'no_match'       => '검색 결과가 없습니다.',
        'no_tools'       => '등록된 도구가 없습니다.',
        'cache_ok'       => 'OBS 캐시 갱신: %s',
        'cache_none'     => 'OBS 캐시 없음',
        'auth_off'       => 'SSO 인증이 <b>비활성</b> 상태입니다. lib/config.php 의 AUTH_MODE 를 <code>sso</code> 로 바꾸면 전환됩니다.',
        'not_found_msg'  => '만약 원하시는 tool을 찾을 수 없다면 아래 링크로 접속해서 찾아주세요.',
        'footer'         => '사내 인프라 개발팀 / 무단 접근을 금지합니다.',
        'generated'      => '생성 시각: %s',
        'confirm_del'    => '"%s" 도구를 삭제할까요? 페이지에서는 되돌릴 수 없습니다.',
        'saved'          => '저장했습니다.',
        'deleted'        => '삭제했습니다.',
        'conflict'       => '수정하는 동안 다른 사람이 표를 변경했습니다. 새로고침 후 다시 시도하세요.',
        'f_tool'         => '도구명',
        'f_prefix'       => 'OBS Prefix',
        'f_os'           => '지원 OS / 아키텍처',
        'f_product'      => '지원 제품군',
        'f_manual'       => '매뉴얼 링크',
        'f_rm_text'      => '비고 — 문구',
        'f_rm_links'     => '비고 — 링크',
        'f_locked'       => 'OBS 자동 — 수정 불가',
        'f_locked_desc'  => '도구 링크 · 이전 버전 · 검증 리포트는 obs_prefix 매칭으로 자동 생성됩니다.',
        'ph_label'       => '라벨',
        'ph_url'         => 'https://...',
        'ph_multi'       => '한 줄에 하나씩',
        'ph_note'        => '예: Emergency Fix',
        'modal_edit'     => '도구 수정 — %s',
        'modal_add'      => '도구 추가',
        'headers'        => ['도구명', '지원 OS / 아키텍처', '지원 제품군',
                             '도구 링크', '검증 리포트', '매뉴얼', '비고'],
    ],
];

function current_lang(): string
{
    if (isset($_GET['lang'])) {
        $lang = $_GET['lang'] === 'ko' ? 'ko' : 'en';
        setcookie('th_lang', $lang, ['expires' => time() + 86400 * 365, 'path' => base_path(), 'samesite' => 'Lax']);
        return $lang;
    }
    return ($_COOKIE['th_lang'] ?? 'en') === 'ko' ? 'ko' : 'en';
}

/** 번역 문자열. 추가 인자는 sprintf 로 채워집니다. */
function tr(string $lang, string $key, ...$args): string
{
    $s = I18N[$lang][$key] ?? I18N['en'][$key] ?? $key;
    if (!is_string($s)) {
        return $key;
    }
    return $args ? vsprintf($s, $args) : $s;
}

/**
 * 페이지가 놓인 하위 경로(예: /release/).
 * 쿠키 경로를 여기로 제한해 같은 도메인의 다른 페이지와 섞이지 않게 합니다.
 */
function base_path(): string
{
    $dir = str_replace('\\', '/', dirname((string)($_SERVER['SCRIPT_NAME'] ?? '/')));
    $dir = rtrim($dir, '/');
    // api/ 안에서 호출되면 한 단계 올라가 프로젝트 루트를 가리키게 합니다.
    if (str_ends_with($dir, '/api')) {
        $dir = substr($dir, 0, -4);
    }
    return ($dir === '' ? '' : $dir) . '/';
}

/** JSON 응답을 내보내고 종료합니다. */
function json_out(array $payload, int $status = 200): never
{
    http_response_code($status);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    exit;
}
